name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  # ViaProxy
  proxy:
    image: endstone/endstone
    container_name: be-server
    command: endstone -y
    ports:
      - "19132:19132/udp"
    volumes:
      - ./run:/app/run
      - ./bedrock_server:/home/endstone/bedrock_server:rw
    stdin_open: true
    tty: true
    networks:
      default:
        ipv4_address: 172.16.238.21

####################################################################################################
# ネットワーク : ネットワークスイッチっぽいやつ？
####################################################################################################
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
