name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  # ViaProxy
  proxy:
    build: .
    image: minecraft/1.21.20/proxy:3.3.4
    container_name: proxy
    volumes:
      - ./run:/app/run
    network_mode: host
