name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  # ViaProxy
  proxy:
    build: .
    image: minecraft/1.21.20/proxy:3.3.4
    container_name: proxy
    volumes:
      - ./run:/app/run
    networks:
      core-dns:
        ipv4_address: 172.16.238.21
    stdin_open: true
    tty: true

####################################################################################################
# ネットワーク : ネットワークスイッチっぽいやつ？
####################################################################################################
networks:
  core-dns:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
