name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  be-server:
    build: .
    image: minecraft/server/jsprismarine
    container_name: minecraft-bedrock-server
    ports:
      - "19132:19132/udp"
    # volumes:
    #   - ./bedrock_server:/app
    stdin_open: true
    tty: true
    networks:
      default:
        ipv4_address: 172.16.238.21

####################################################################################################
# ネットワーク : ネットワークスイッチっぽいやつ？
####################################################################################################
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
