####################################################################################################
# マインクラフトサーバーに必要なものを用意するための Docker Compose ファイル
# 
# ポート一覧
#  53: DNS用ポート
#  19132: Switch用 外部サーバー接続用サーバー
#  20000: マイクラサーバー
####################################################################################################
name: Minecraft

####################################################################################################
# サービス
####################################################################################################
services:
  # # Alpine Linux 調査や実験に使用
  # alpine:
  #   image: alpine:latest
  #   container_name: alpines
  #   networks:
  #     core-dns:
  #   dns:
  #     - 172.16.238.10
  #   stdin_open: true
  #   tty: true

  # CoreDNS Distroless サーバー
  coredns:
    build:
      context: ./Dockerfiles
      dockerfile: CoreDNS.Dockerfile
    image: minecraft/dns/server:latest
    container_name: coredns
    configs:
      - source: coredns
        target: /etc/coredns/Corefile
    networks:
      core-dns:
        ipv4_address: 172.16.238.10
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    stdin_open: true
    tty: true

  # Switch用特集サーバー (BedrockConnect)
  connector:
    build:
      context: ./Dockerfiles
      dockerfile: BedrockConnect.Dockerfile
    image: minecraft/1.21/jdk/21/connector/bedrockconnect:1.49
    container_name: connector
    networks:
      core-dns:
        ipv4_address: 172.16.238.11
    ports:
      - "19132:19132/udp"
    stdin_open: true
    tty: true

  # Minecraft Server
  server:
    build:
      context: ./Dockerfiles
      dockerfile: Minecraft.Dockerfile
    image: minecraft/1.21/jdk/21/server/pufferfish:1.21.1
    container_name: server
    volumes:
      - ./Data/config:/opt/srv/minecraft/config
      - ./Data/worlds:/opt/srv/minecraft/worlds
      - ./Data/plugins:/opt/srv/minecraft/plugins
      - ./Data/data:/opt/srv/minecraft/data
      - ./Data/logs:/opt/srv/minecraft/logs
    networks:
      core-dns:
        ipv4_address: 172.16.238.21
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    stdin_open: true
    tty: true

####################################################################################################
# 設定情報 : ホスト上のローカルファイルを指定する場所
####################################################################################################
configs:
  coredns:
    file: ./Configs/CoreDNS/Corefile

####################################################################################################
# ネットワーク : ネットワークスイッチっぽいやつ？
####################################################################################################
networks:
  core-dns:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
